### ISSUE TITLE
SIGSEGV in eglInitialize

### ISSUE THREAD

**Issue by kvark** [timothee-haudebourg/khronos-egl#10]
I'm seeing SIGSEGV when running tests in gfx-rs repo:
```
Thread 1 "reftest" received signal SIGSEGV, Segmentation fault.
0x00007ffff76b9a80 in ?? ()
(gdb) bt
#0  0x00007ffff76b9a80 in ?? ()
#1  0x00007ffff780bd4e in ?? () from /usr/lib/libxcb.so.1
#2  0x00007ffff780c19e in ?? () from /usr/lib/libxcb.so.1
#3  0x00007ffff780cee9 in xcb_send_request () from /usr/lib/libxcb.so.1
#4  0x00007ffff781ef04 in xcb_query_extension () from /usr/lib/libxcb.so.1
#5  0x00007ffff780fe51 in xcb_prefetch_extension_data () from /usr/lib/libxcb.so.1
#6  0x00007ffff78cc793 in ?? () from /usr/lib/libEGL_mesa.so.0
#7  0x00007ffff78cbac8 in ?? () from /usr/lib/libEGL_mesa.so.0
#8  0x00007ffff78c6b23 in ?? () from /usr/lib/libEGL_mesa.so.0
#9  0x00007ffff78c2c3d in ?? () from /usr/lib/libEGL_mesa.so.0
#10 0x00007ffff78c2c8a in ?? () from /usr/lib/libEGL_mesa.so.0
#11 0x00007ffff78bd298 in ?? () from /usr/lib/libEGL_mesa.so.0
#12 0x0000555555b472ab in <khronos_egl::Dynamic<L> as khronos_egl::Api>::eglInitialize (self=0x5555560f1db0, display=0x55555651e620, major=0x7fffffffc050, 
    minor=0x7fffffffc054) at /home/kvark/.cargo/git/checkouts/khronos-egl-96ea0eb5fe3f44af/9568b2e/src/lib.rs:1601
#13 khronos_egl::Instance<T>::initialize (self=0x5555560f1db0, display=...)
    at /home/kvark/.cargo/git/checkouts/khronos-egl-96ea0eb5fe3f44af/9568b2e/src/lib.rs:867
```

Repro steps:
  1. Check out https://github.com/gfx-rs/gfx/pull/3542, or the revision of master when it lands
  2. Run `make reftests` on Linux within the `gfx` folder.

This may very well be something wrong I'm doing, but I haven't figured it out yet. Just filing here in case you could help me.

**Comment by kvark** [comment]
Ok, I figured this out. I'm loading X11 and dropping the library before using the handle.
